# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: DeepPocket

channels:
  - pytorch
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.9.16 #added
  - pytorch=2.* #added
  - torchvision=0.* #added
  - lightning=2.* #added
  - torchmetrics=0.* #added
  - hydra-core=1.* #added
  - rich=13.* #added
  - pre-commit=3.* #added
  - pytest=7.* #added

  # --------- loggers --------- #
  - wandb #added
  - neptune-client #added
  - mlflow #added
  # - comet-ml
  - aim>=3.16.2 # no lower than 3.16.2, see https://github.com/aimhubio/aim/issues/2550

  - pip>=23
  - pip:
      - hydra-optuna-sweeper
      - hydra-colorlog
      - pyrootutils
