_target_: src.models.deepPocketRSEModule.DeepPocketRSELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

encoderNet:
  _target_: src.models.components.RSENet.RSENetEncoder
  inputSize: 11
  encoder1Size: 10
  encoder2Size: 9
  encoderOutputSize: 3
  dropoutRate: 0.3

decoderNet:
  _target_: src.models.components.RSENet.RSENetDecoder
  decoderInputSize: 3
  decoder1Size: 3
  decoder2Size: 3
  outputSize: 3
  dropoutRate: 0.3
