# @package _global_

defaults:
  - _self_
  - data: rse.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: rse.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /Users/barbod/Developer/finTech/DeepPocketImplement/logs/train/runs/2023-07-02_10-55-26/checkpoints/epoch_089.ckpt
